Models/Books.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVCBookStore.Models
{
    public class Books
    {
        [Required]
        public int Id { get; set; }

        [StringLength(100)]
        [Required]
        public string Title { get; set; }

        [Display(Name = "Year Published")]
        public int? YearPublished { get; set; }

        [Display(Name = "Number of Pages")]
        public int? NumPages { get; set; }


        public string? Description { get; set; }

        [StringLength(50)]
        public string? Publisher { get; set; }

        [Display(Name = "Front Page")]
        public string? FrontPage { get; set; }

        [Display(Name = "Download")]
        public string? DownloadUrl { get; set; }

        //external keys
        [Display(Name = "Author")]
        public int AuthorId { get; set; }
        public Author? Author { get; set; }

        [Display(Name = "Genres")]
        public ICollection<BookGenre>? Genres { get; set; }
        public ICollection<Review>? Reviews { get; set; }
        public ICollection<UserBooks>? UserBooks { get; set; }

        [NotMapped]

        [Display(Name = "Average Rating")]
        public double Average
        {
            get
            {
                if (Reviews == null)
                    return 0;

                double average = 0;
                int i = 0;
                if (Reviews != null)
                {
                    foreach (var review in Reviews)
                    {
                        average += review.Rating;
                        i++;
                    }

                    return Math.Round(average / i, 2);
                }
                return 0;
            }
        }
    }
}

Controllers/BooksController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCBookStore.Data;
using MVCBookStore.Models;
using MVCBookStore.ViewModels;

namespace MVCBookStore.Controllers
{
    public class BooksController : Controller
    {
        private readonly MVCBookStoreContext _context;
        private readonly IWebHostEnvironment webHostEnvironment;

        public BooksController(MVCBookStoreContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            webHostEnvironment = hostEnvironment;
        }




        // GET: Books, implement searching here!
        public async Task<IActionResult> Index(string title, string genre)
        {
            var booksQuery = _context.Books.
                Include(b => b.Author).
                Include(b => b.Reviews).
                Include(b => b.Genres).
                ThenInclude(b => b.Genre);
            var genresQuery = _context.BookGenre.Include(b => b.Genre).Include(b => b.Books);
            var genres = from n in genresQuery select n;
            var books = from m in booksQuery select m;
             

            if (!string.IsNullOrEmpty(title))
            {
                books = books.Where(x => x.Title.Contains(title));
            }
            if (!string.IsNullOrEmpty(genre))
            {
                genres = genres.Where(s => s.Genre.GenreName!.Contains(genre));
                var innerJoinQuery =
                 from m in books
                 join n in genres on m.Id equals n.BooksId
                 select new { m };
                ArrayList lista = new ArrayList();

                foreach (var bookAndGenre in innerJoinQuery)
                {

                    lista.Add(bookAndGenre.m);
                }

                ViewBag.lista = lista;
            }

            return View(await books.ToListAsync());
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }

            var books = await _context.Books
                .Include(b => b.Author)
                .Include(b => b.Reviews)
                .Include(m => m.Genres)
                .ThenInclude(m => m.Genre)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (books == null)
            {
                return NotFound();
            }

            return View(books);
        }

        // GET: Books/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create(Books book)
        {
            ViewData["AuthorId"] = new SelectList(_context.Author, "Id", "FullName", book.AuthorId);
            ViewData["Genres"] = new MultiSelectList(_context.Set<Genre>(), "Id", "GenreName");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([FromForm] BookViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileNameIMG = UploadedFile(model);
                string uniqueFileNamePDF = UploadedPdf(model);

                Books book = new Books
                {
                    Title = model.Title,
                    YearPublished = model.YearPublished,
                    NumPages = model.NumPages,
                    Description = model.Description,
                    Publisher = model.Publisher,
                    FrontPage = uniqueFileNameIMG,
                    DownloadUrl = uniqueFileNamePDF,
                    AuthorId = model.AuthorId
                };
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Set<Author>(), "Id", "FullName", model.AuthorId);
            return View();
        }

        //Uploading Images
        private string UploadedFile(BookViewModel model)
        {
            string uniqueFileNameIMG = null;
            string uniqueFileNamePDF = null;

            if (model.FrontPageVM != null)
            {
                string uploadsFolderIMG = Path.Combine(webHostEnvironment.WebRootPath, "images");
                uniqueFileNameIMG = Guid.NewGuid().ToString() + "_" + Path.GetFileName(model.FrontPageVM.FileName);
                string filePath = Path.Combine(uploadsFolderIMG, uniqueFileNameIMG);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.FrontPageVM.CopyTo(fileStream);
                }
            }
            return uniqueFileNameIMG;
        }

        //Downloading the File
        public async Task<IActionResult> GetPDF(string url)
        {
            string RenameFile = url;
            var path = Path.Combine(
            Directory.GetCurrentDirectory(), "wwwroot/pdfs/" + url);

            var memory = new MemoryStream();
            using (var stream = new FileStream(path, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;

            return File(memory, "application/pdf", RenameFile);
        }

        private string GetFileName(BookViewModel model)
        {
            return model.DownloadUrlVM.FileName;
        }

        //Uploading Files
        private string UploadedPdf(BookViewModel model)
        {

            string uniqueFileNamePDF = null;

            if (model.DownloadUrlVM != null)
            {
                string uploadsFolderPDF = Path.Combine(webHostEnvironment.WebRootPath, "pdfs");
                uniqueFileNamePDF = Guid.NewGuid().ToString() + "_" + model.DownloadUrlVM.FileName;
                string filePathh = Path.Combine(uploadsFolderPDF, uniqueFileNamePDF);
                using (var fileStreamm = new FileStream(filePathh, FileMode.Create))
                {
                    model.DownloadUrlVM.CopyTo(fileStreamm);
                }
            }

            return uniqueFileNamePDF;
        }

        // GET: Books/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }

            var books = _context.Books.Where(m => m.Id == id).Include(m => m.Genres).First();
            if (books == null)
            {
                return NotFound();
            }

            var genres = _context.Genre.AsEnumerable();
            genres = genres.OrderBy(s => s.GenreName);

            BookGenresEditViewModel viewmodel = new BookGenresEditViewModel
            {
                Book = books,
                GenreList = new MultiSelectList(genres, "Id", "GenreName"),
                SelectedGenres = books.Genres.Select(sa => sa.GenreId)
            };


            ViewData["AuthorId"] = new SelectList(_context.Set<Author>(), "Id", "FirstName", books.AuthorId);
            return View(viewmodel);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, BookGenresEditViewModel viewmodel)
        {
            if (id != viewmodel.Book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(viewmodel.Book);
                    await _context.SaveChangesAsync();

                    //Genres
                    IEnumerable<int> newGenreList = viewmodel.SelectedGenres;
                    IEnumerable<int> prevGenreList = _context.BookGenre.Where(s => s.BooksId == id).Select(s => s.GenreId);
                    IQueryable<BookGenre> toBeRemoved = _context.BookGenre.Where(s => s.BooksId == id);
                    if (newGenreList != null)
                    {
                        toBeRemoved = toBeRemoved.Where(s => !newGenreList.Contains(s.GenreId));
                        foreach (int genreId in newGenreList)
                        {
                            if (!prevGenreList.Any(s => s == genreId))
                            {
                                _context.BookGenre.Add(new BookGenre { GenreId = genreId, BooksId = id });
                            }
                        }
                    }
                    _context.BookGenre.RemoveRange(toBeRemoved);

                    string uniqueFileNameIMG = null;
                    if (viewmodel.FrontPageEVM != null)
                    {
                        string uploadsFolderIMG = Path.Combine(webHostEnvironment.WebRootPath, "images");
                        uniqueFileNameIMG = viewmodel.FrontPageEVM.FileName;
                        string filePath = Path.Combine(uploadsFolderIMG, uniqueFileNameIMG);
                        using (var fileStream = new FileStream(filePath, FileMode.Create))

Controllers/UserBooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCBookStore.Data;
using MVCBookStore.Models;

namespace MVCBookStore.Controllers
{
    public class UserBooksController : Controller
    {
        private readonly MVCBookStoreContext _context;

        public UserBooksController(MVCBookStoreContext context)
        {
            _context = context;
        }

        // GET: UserBooks
        [Authorize(Roles = "User")]
        public async Task<IActionResult> Index()
        {
            var workshopImprovedContext = _context.UserBooks.Include(u => u.Books);
            return View(await workshopImprovedContext.ToListAsync());
        }

        // GET: UserBooks/Details/5
        [Authorize(Roles = "User")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.UserBooks == null)
            {
                return NotFound();
            }

            var userBooks = await _context.UserBooks
                .Include(u => u.Books)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userBooks == null)
            {
                return NotFound();
            }

            return View(userBooks);
        }

        // GET: UserBooks/Create
        [Authorize(Roles = "User")]
        public IActionResult Create()
        {
            ViewData["BooksId"] = new SelectList(_context.Books, "Id", "Title");
            return View();
        }

        // POST: UserBooks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User")]
        public async Task<IActionResult> Create([Bind("Id,AppUser,BooksId")] UserBooks userBooks)
        {
            if (ModelState.IsValid)
            {
                userBooks.AppUser = HttpContext.User.Identity.Name;
                _context.Add(userBooks);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BooksId"] = new SelectList(_context.Books, "Id", "Title", userBooks.BooksId);
            return View(userBooks);
        }

        // GET: UserBooks/Edit/5
        [Authorize(Roles = "User")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.UserBooks == null)
            {
                return NotFound();
            }

            var userBooks = await _context.UserBooks.FindAsync(id);
            if (userBooks == null)
            {
                return NotFound();
            }
            ViewData["BooksId"] = new SelectList(_context.Books, "Id", "Title", userBooks.BooksId);
            return View(userBooks);
        }

        // POST: UserBooks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,AppUser,BooksId")] UserBooks userBooks)
        {
            if (id != userBooks.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userBooks);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserBooksExists(userBooks.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BooksId"] = new SelectList(_context.Books, "Id", "Title", userBooks.BooksId);
            return View(userBooks);
        }

        // GET: UserBooks/Delete/5
        [Authorize(Roles = "User")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.UserBooks == null)
            {
                return NotFound();
            }

            var userBooks = await _context.UserBooks
                .Include(u => u.Books)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userBooks == null)
            {
                return NotFound();
            }

            return View(userBooks);
        }

        // POST: UserBooks/Delete/5
        [Authorize(Roles = "User")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.UserBooks == null)
            {
                return Problem("Entity set 'MVCBookStoreContext.UserBooks'  is null.");
            }
            var userBooks = await _context.UserBooks.FindAsync(id);
            if (userBooks != null)
            {
                _context.UserBooks.Remove(userBooks);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserBooksExists(int id)
        {
          return (_context.UserBooks?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Books/Details.cshtml
@model MVCBookStore.Models.Books

@{
    ViewData["Title"] = "Details";
}

<h1>Book Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FrontPage)
        </dt>
        <dd class = "col-sm-10">
            @if (File.Exists(($"C:/Users/Bobi/source/repos/MVCBookStore/wwwroot/images/{Model.FrontPage}")))
            {
                <img src=@("~/images/" + Model.FrontPage)
                     height="200" width="140"
                 asp-append-version="true" />
            }
            else
            {
                <img src="@Model.FrontPage"
                     height="200" width="140"
                 asp-append-version="true" />
            }
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.YearPublished)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.YearPublished)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumPages)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumPages)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Publisher)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Genres)
        </dt>
        <dd class="col-sm-10">
            @if (Model.Genres != null)
            {
                @foreach (var genre in Model.Genres)
                {
                    <a asp-controller="Genres" asp-action="Details" asp-route-id="@genre.GenreId">
                        @genre.Genre.GenreName
                    </a> <br />
                }
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Average)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Average)
        </dd>
        <dt class="col-sm-2"></dt>
        <dd class = "col-sm-10">
             @if (User.Identity.IsAuthenticated && (User.IsInRole("Admin"))){
                <form a asp-action="GetPDF" asp-controller="Books">
                    <input name="url" type="hidden" value="@Html.DisplayFor(model => model.DownloadUrl)">
                    <button class="btn btn-info" type="submit" value="Download pdf">Download</button><br>
                </form>
             }
        </dd>

        <div style="margin: 25px;"></div>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Reviews)
        </dt>
        <dd class="col-sm-10">
            @if (Model.Reviews != null)
            {
                <dl class="row"><hr>
                    @foreach (var review in Model.Reviews)
                    {
                        <dt class="col-sm-2">
                            User: 
                        </dt>
                        <dd class="col-sm-10">
                            @review.AppUser
                        </dd>
                        <dt class="col-sm-2">
                            Comment: 
                        </dt>
                        <dd class="col-sm-10">
                            @review.Comment
                        </dd>
                        <dt class="col-sm-2">
                            Rating: 
                        </dt>
                        <dd class="col-sm-10">
                            @review.Rating
                        </dd>
                        <hr/>
                    }
                </dl>
            }
        </dd>
    </dl>
</div>
<div>
    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
    {
        <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a>
    }
    <a asp-action="Index">Back to List</a>
    @if (User.Identity.IsAuthenticated && User.IsInRole("User"))
    {
        <a asp-action="Index" asp-controller="UserBooks">Back to My Books</a>
    }
</div>

Views/Books/Edit.cshtml
@model MVCBookStore.ViewModels.BookGenresEditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit a Book</h1>

<hr />
<div class="col-md-10 mx-auto py-4">
    <div class="card">
        <div class="card-header bg-primary text-uppercase text-white">
            <h4>Edit Books</h4>
        </div>
        <div class="card-body">
            <form enctype="multipart/form-data" asp-controller="Books" asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Book.Id" />
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="Book.Title" class="control-label"></label>
                            <input asp-for="Book.Title" class="form-control" />
                            <span asp-validation-for="Book.Title" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="Book.YearPublished" class="control-label"></label>
                            <input asp-for="Book.YearPublished" class="form-control" />
                            <span asp-validation-for="Book.YearPublished" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="Book.NumPages" class="control-label"></label>
                            <input asp-for="Book.NumPages" class="form-control" />
                            <span asp-validation-for="Book.NumPages" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="Book.Publisher" class="control-label"></label>
                            <input asp-for="Book.Publisher" class="form-control" />
                            <span asp-validation-for="Book.Publisher" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                                <label asp-for="Book.Description" class="control-label"></label>
                                <input asp-for="Book.Description" class="form-control" />
                                <span asp-validation-for="Book.Description" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="Book.AuthorId" class="control-label"></label>
                            <select asp-for="Book.AuthorId" class ="form-control" asp-items="ViewBag.AuthorId"></select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="FrontPageEVM" class="control-label"></label>
                            <div class="custom-file">
                                <input asp-for="FrontPageEVM" class="custom-file-input" id="customFile" />
                                <label class="custom-file-label" for="customFile"></label>
                            </div>
                            <span asp-validation-for="FrontPageEVM" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="DownloadUrlEVM" class="control-label"></label>
                            <div class="custom-file">
                                <input asp-for="DownloadUrlEVM" class="custom-file-input" id="customFile" />
                                <label class="custom-file-label" for="customFile"></label>
                            </div>
                            <span asp-validation-for="DownloadUrlEVM" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">Genres</label>
                            <select asp-for="SelectedGenres" class="form-control js-example-basic-multiple" asp-items="Model.GenreList"></select>
                            <span asp-validation-for="SelectedGenres" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="form-group" style="margin:15px 0 15px 0;">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Books/Index.cshtml
@model IEnumerable<MVCBookStore.Models.Books>

@{
    ViewData["Title"] = "Index";
}

<h1>Books</h1>

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <p>
        <a asp-action="Create">Insert New Books</a>
    </p>
}
<form asp-controller="Books" asp-action="Index">
    <p>
        Title: <input type="text" name="title" />
        Genre: <input type="text" name="genre" />
        
        <input type="submit" value="Filter" />
    </p>
</form>


<div class="row row-cols-3 g-3" style="display:flex; justify-content: space-between; ">
    @foreach(var item in Model){
        <div class="card" style="margin:10px; width:300px; padding:0px;">
            <img class="card-img-top" src="~/images/@item.FrontPage" alt="book front page" width="300px" asp-append-version="true"/> 
            <div class="card-body">
                <div style="display: flex; flex-direction: column;">
                    <h5 class="card-title">@item.Title</h5>
                    <p class="card-text"><strong>@Html.DisplayNameFor(model => model.Author):</strong> @Html.DisplayFor(modelItem => item.Author.FullName)</p>
                    <p class="card-text"><strong>@Html.DisplayNameFor(model => model.YearPublished):</strong> @item.YearPublished</p>
                    <p class="card-text"><strong>@Html.DisplayNameFor(model => model.NumPages):</strong> @item.NumPages</p>
                    <p class="card-text"><strong>@Html.DisplayNameFor(model => model.Publisher):</strong> @item.Publisher</p>
                    <div>
                        @if (User.Identity.IsAuthenticated && (User.IsInRole("Admin")))
                        {
                            <form a asp-action="GetPDF" asp-controller="Books">
                                <input name="url" type="hidden" value="@item.DownloadUrl">
                                <button class="btn btn-info" type="submit" value="Download pdf">Download</button><br>
                            </form>
                        }
                    </div>
                    <div id="spacer" style="width: 200px; height: 25px; margin-right:0px;"></div>
                    <div class="bottomleft">
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                        }
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        }
                    </div>
                </div>
                
            </div>
        </div>
    }
</div>