Models/Author.cs
using System.ComponentModel.DataAnnotations;

namespace MVCBookStore.Models
{
    public class Author
    {
        public int Id { get; set; }

        [Required]
        [MaxLength(50)]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [MaxLength(50)]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Birth Date")]
        public DateTime? BirthDate { get; set; }

        [MaxLength(50)]
        public string? Nationality { get; set; }

        [MaxLength(50)]
        public string? Gender { get; set; }

        public string FullName
        {
            get { return String.Format("{0} {1}", FirstName, LastName); }
        }

        public ICollection<Books>? Books { get; set; }

    }
}

Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCBookStore.Data;
using MVCBookStore.Models;
using MVCBookStore.ViewModels;

namespace MVCBookStore.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly MVCBookStoreContext _context;

        public AuthorsController(MVCBookStoreContext context)
        {
            _context = context;
        }

        // GET: Authors
        public async Task<IActionResult> Index(string FullNameAuthor, string Nationality)
        {
            IQueryable<Author> authorsQuery = _context.Author.AsQueryable();
            if (!string.IsNullOrEmpty(FullNameAuthor))
            {
                if (FullNameAuthor.Contains(" "))
                {
                    string[] names = FullNameAuthor.Split(" ");
                    
                    authorsQuery = authorsQuery.Where(
                        x => x.FirstName.Contains(names[0]) && x.LastName.Contains(names[1]) ||
                        x.FirstName.Contains(names[1]) && x.LastName.Contains(names[0])
                    );
                }
                else
                {
                    authorsQuery = authorsQuery.Where(x => x.FirstName.Contains(FullNameAuthor) || x.LastName.Contains(FullNameAuthor));
                }
            }

            if (!string.IsNullOrEmpty(Nationality))
            {
                authorsQuery = authorsQuery.Where(c => c.Nationality.Contains(Nationality));
            }

            var AuthorFilterVM = new AuthorFilter
            {
                Authors = await authorsQuery.ToListAsync()
            };

            return View(AuthorFilterVM);
        }

        // GET: Authors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Author == null)
            {
                return NotFound();
            }

            var author = await _context.Author
                .Include(b => b.Books)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // GET: Authors/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,BirthDate,Nationality,Gender")] Author author)
        {
            if (ModelState.IsValid)
            {
                _context.Add(author);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Author == null)
            {
                return NotFound();
            }

            var author = await _context.Author.FindAsync(id);
            if (author == null)
            {
                return NotFound();
            }
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,BirthDate,Nationality,Gender")] Author author)
        {
            if (id != author.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(author);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AuthorExists(author.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Author == null)
            {
                return NotFound();
            }

            var author = await _context.Author
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // POST: Authors/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Author == null)
            {
                return Problem("Entity set 'MVCBookStoreContext.Author'  is null.");
            }
            var author = await _context.Author.FindAsync(id);
            if (author != null)
            {
                _context.Author.Remove(author);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AuthorExists(int id)
        {
          return (_context.Author?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/BooksController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCBookStore.Data;
using MVCBookStore.Models;
using MVCBookStore.ViewModels;

namespace MVCBookStore.Controllers
{
    public class BooksController : Controller
    {
        private readonly MVCBookStoreContext _context;
        private readonly IWebHostEnvironment webHostEnvironment;

        public BooksController(MVCBookStoreContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            webHostEnvironment = hostEnvironment;
        }




        // GET: Books, implement searching here!
        public async Task<IActionResult> Index(string title, string genre)
        {
            var booksQuery = _context.Books.
                Include(b => b.Author).
                Include(b => b.Reviews).
                Include(b => b.Genres).
                ThenInclude(b => b.Genre);
            var genresQuery = _context.BookGenre.Include(b => b.Genre).Include(b => b.Books);
            var genres = from n in genresQuery select n;
            var books = from m in booksQuery select m;
             

            if (!string.IsNullOrEmpty(title))
            {
                books = books.Where(x => x.Title.Contains(title));
            }
            if (!string.IsNullOrEmpty(genre))
            {
                genres = genres.Where(s => s.Genre.GenreName!.Contains(genre));
                var innerJoinQuery =
                 from m in books
                 join n in genres on m.Id equals n.BooksId
                 select new { m };
                ArrayList lista = new ArrayList();

                foreach (var bookAndGenre in innerJoinQuery)
                {

                    lista.Add(bookAndGenre.m);
                }

                ViewBag.lista = lista;
            }

            return View(await books.ToListAsync());
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }

            var books = await _context.Books
                .Include(b => b.Author)
                .Include(b => b.Reviews)
                .Include(m => m.Genres)
                .ThenInclude(m => m.Genre)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (books == null)
            {
                return NotFound();
            }

            return View(books);
        }

        // GET: Books/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create(Books book)
        {
            ViewData["AuthorId"] = new SelectList(_context.Author, "Id", "FullName", book.AuthorId);
            ViewData["Genres"] = new MultiSelectList(_context.Set<Genre>(), "Id", "GenreName");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([FromForm] BookViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileNameIMG = UploadedFile(model);
                string uniqueFileNamePDF = UploadedPdf(model);

                Books book = new Books
                {
                    Title = model.Title,
                    YearPublished = model.YearPublished,
                    NumPages = model.NumPages,
                    Description = model.Description,
                    Publisher = model.Publisher,
                    FrontPage = uniqueFileNameIMG,
                    DownloadUrl = uniqueFileNamePDF,
                    AuthorId = model.AuthorId
                };
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Set<Author>(), "Id", "FullName", model.AuthorId);
            return View();
        }

        //Uploading Images
        private string UploadedFile(BookViewModel model)
        {
            string uniqueFileNameIMG = null;
            string uniqueFileNamePDF = null;

            if (model.FrontPageVM != null)
            {
                string uploadsFolderIMG = Path.Combine(webHostEnvironment.WebRootPath, "images");
                uniqueFileNameIMG = Guid.NewGuid().ToString() + "_" + Path.GetFileName(model.FrontPageVM.FileName);
                string filePath = Path.Combine(uploadsFolderIMG, uniqueFileNameIMG);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.FrontPageVM.CopyTo(fileStream);
                }
            }
            return uniqueFileNameIMG;
        }

        //Downloading the File
        public async Task<IActionResult> GetPDF(string url)
        {
            string RenameFile = url;
            var path = Path.Combine(
            Directory.GetCurrentDirectory(), "wwwroot/pdfs/" + url);

            var memory = new MemoryStream();
            using (var stream = new FileStream(path, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;

            return File(memory, "application/pdf", RenameFile);
        }

        private string GetFileName(BookViewModel model)
        {
            return model.DownloadUrlVM.FileName;
        }

        //Uploading Files
        private string UploadedPdf(BookViewModel model)
        {

            string uniqueFileNamePDF = null;

            if (model.DownloadUrlVM != null)
            {
                string uploadsFolderPDF = Path.Combine(webHostEnvironment.WebRootPath, "pdfs");
                uniqueFileNamePDF = Guid.NewGuid().ToString() + "_" + model.DownloadUrlVM.FileName;
                string filePathh = Path.Combine(uploadsFolderPDF, uniqueFileNamePDF);
                using (var fileStreamm = new FileStream(filePathh, FileMode.Create))
                {
                    model.DownloadUrlVM.CopyTo(fileStreamm);
                }
            }

            return uniqueFileNamePDF;
        }

        // GET: Books/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }

            var books = _context.Books.Where(m => m.Id == id).Include(m => m.Genres).First();
            if (books == null)
            {
                return NotFound();
            }

            var genres = _context.Genre.AsEnumerable();
            genres = genres.OrderBy(s => s.GenreName);

            BookGenresEditViewModel viewmodel = new BookGenresEditViewModel
            {
                Book = books,
                GenreList = new MultiSelectList(genres, "Id", "GenreName"),
                SelectedGenres = books.Genres.Select(sa => sa.GenreId)
            };


            ViewData["AuthorId"] = new SelectList(_context.Set<Author>(), "Id", "FirstName", books.AuthorId);
            return View(viewmodel);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, BookGenresEditViewModel viewmodel)
        {
            if (id != viewmodel.Book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(viewmodel.Book);
                    await _context.SaveChangesAsync();

                    //Genres
                    IEnumerable<int> newGenreList = viewmodel.SelectedGenres;
                    IEnumerable<int> prevGenreList = _context.BookGenre.Where(s => s.BooksId == id).Select(s => s.GenreId);
                    IQueryable<BookGenre> toBeRemoved = _context.BookGenre.Where(s => s.BooksId == id);
                    if (newGenreList != null)
                    {
                        toBeRemoved = toBeRemoved.Where(s => !newGenreList.Contains(s.GenreId));
                        foreach (int genreId in newGenreList)
                        {
                            if (!prevGenreList.Any(s => s == genreId))
                            {
                                _context.BookGenre.Add(new BookGenre { GenreId = genreId, BooksId = id });
                            }
                        }
                    }
                    _context.BookGenre.RemoveRange(toBeRemoved);

                    string uniqueFileNameIMG = null;
                    if (viewmodel.FrontPageEVM != null)
                    {
                        string uploadsFolderIMG = Path.Combine(webHostEnvironment.WebRootPath, "images");
                        uniqueFileNameIMG = viewmodel.FrontPageEVM.FileName;
                        string filePath = Path.Combine(uploadsFolderIMG, uniqueFileNameIMG);
                        using (var fileStream = new FileStream(filePath, FileMode.Create))

Views/Authors/Create.cshtml
@model MVCBookStore.Models.Author

@{
    ViewData["Title"] = "Create";
}

<h1>Create Authors</h1>

<hr />
<div class="col-md-10 mx-auto py-4">
    <div class="card">
        <div class="card-header bg-primary text-uppercase text-white">
            <h4>Insert New Authors</h4>
        </div>
        <div class="card-body">
            <form enctype="multipart/form-data" asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="FirstName" class="control-label"></label>
                            <input asp-for="FirstName" class="form-control" />
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="LastName" class="control-label"></label>
                            <input asp-for="LastName" class="form-control" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="BirthDate" class="control-label"></label>
                            <input asp-for="BirthDate" class="form-control" />
                            <span asp-validation-for="BirthDate" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="Nationality" class="control-label"></label>
                            <input asp-for="Nationality" class="form-control" />
                            <span asp-validation-for="Nationality" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
							<label asp-for="Gender" class="control-label"></label>
							<select asp-for="Gender" class="form-control js-example-basic-multiple">
								<option value="Male">Male</option>
								<option value="Female">Female</option>
							</select>
							<span asp-validation-for="Gender" class="text-danger"></span>
						</div>
                    </div>
                </div>
               
                <div class="form-group" style="margin:15px 0 15px 0;">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Authors/Delete.cshtml
@model MVCBookStore.Models.Author

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Author</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nationality)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nationality)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Authors/Details.cshtml
@model MVCBookStore.Models.Author

@{
    ViewData["Title"] = "Details";
}

<h1>Author Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nationality)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nationality)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Books)
        </dt>
        <dd class="col-sm-10">
            @if (Model.Books != null)
            {
                @foreach (var books in Model.Books)
                {
                    <a asp-controller="Books" asp-action="Details" asp-route-id="@books.Id">
                        @books.Title
                    </a> <br />
                }
            }
        </dd>
    </dl>
</div>
<div>
    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
    {
        <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a>
    }
    <a asp-action="Index">Back to List</a>
</div>

Views/Authors/Edit.cshtml
@model MVCBookStore.Models.Author

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit an Author</h1>

<hr />

<div class="col-md-10 mx-auto py-4">
    <div class="card">
        <div class="card-header bg-primary text-uppercase text-white">
            <h4>Insert New Authors</h4>
        </div>
        <div class="card-body">
            <form enctype="multipart/form-data" asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="FirstName" class="control-label"></label>
                            <input asp-for="FirstName" class="form-control" />
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="LastName" class="control-label"></label>
                            <input asp-for="LastName" class="form-control" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="BirthDate" class="control-label"></label>
                            <input asp-for="BirthDate" class="form-control" />
                            <span asp-validation-for="BirthDate" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="Nationality" class="control-label"></label>
                            <input asp-for="Nationality" class="form-control" />
                            <span asp-validation-for="Nationality" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
							<label asp-for="Gender" class="control-label"></label>
							<select asp-for="Gender" class="form-control js-example-basic-multiple">
								<option value="Male">Male</option>
								<option value="Female">Female</option>
							</select>
							<span asp-validation-for="Gender" class="text-danger"></span>
						</div>
                    </div>
                </div>
               
                <div class="form-group" style="margin:15px 0 15px 0;">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Authors/Index.cshtml
@model MVCBookStore.ViewModels.AuthorFilter

@{
    ViewData["Title"] = "Index";
}

<h1>Authors</h1>

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}

<form asp-controller="Authors" asp-action="Index" method="get">
    <p>
        Name or Surname: <input type="text" asp-for="FullNameAuthor" />
        Nationality: <input type="text" asp-for="Nationality" />
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Authors[0].FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Authors[0].LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Authors[0].BirthDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nationality)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Authors[0].Gender)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Authors) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nationality)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                }
                <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                }
            </td>
        </tr>
}
    </tbody>
</table>